In [31]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd().parent
DATA_DIR = BASE_DIR / "data"
INPUT_JSONL = DATA_DIR / "extracted" / "extracted_desc_20260407_023403.jsonl"
df = pd.read_json(INPUT_JSONL, orient="records", lines=True)

In [32]:
# 将df的extracted列展开为多列，并将这些列添加到df中，最后删除extracted列
extracted_df = df["extracted"].apply(pd.Series)
processed_df = pd.concat([df.drop(columns=["extracted"]), extracted_df], axis=1)
# 把status列取值为skipped_empty_desc的行去掉，便于观察
processed_df = processed_df[processed_df["status"] != "skipped_empty_desc"]
processed_df.head(5)

,id,name,fullDesc,status,material,pattern,shape,state,color,craft,raw_excavation_info,raw_size_in_desc,other_info
0,05EB474CCFC646D6A4B7184EB047DA09,新石器时代大汶口文化灰陶环,暂无描述,success,灰陶,None,None,None,None,None,None,None,None
1,424ef49f0ed143fe8834415acda7f1e7,新石器时代大汶口文化黑陶高柄杯,暂无描述,success,None,None,高柄,None,黑陶,None,None,None,None
2,ABE33DEB2BF94D3B95A313E93F60DB71,新石器时代大汶口文化灰陶罐,暂无描述,success,灰陶,None,罐,None,None,None,None,None,None
3,88EBDFF0B8B7497995CB37BA5417A033,新石器时代大汶口文化红褐陶器盖,暂无描述,success,红褐陶,None,None,None,None,None,None,None,None
4,060D1DCF727446EABCC62996C9357A29,新石器时代大汶口文化白陶器,暂无描述,success,白陶,None,器,None,None,None,None,None,None

In [33]:
processed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   4119 non-null   object
 1   name                 4119 non-null   object
 2   fullDesc             4119 non-null   object
 3   status               4119 non-null   object
 4   material             2842 non-null   object
 5   pattern              299 non-null    object
 6   shape                2635 non-null   object
 7   state                96 non-null     object
 8   color                1208 non-null   object
 9   craft                297 non-null    object
 10  raw_excavation_info  103 non-null    object
 11  raw_size_in_desc     82 non-null     object
 12  other_info           266 non-null    object
dtypes: object(13)
memory usage: 418.5+ KB

In [46]:
# 将提取数据与原始数据按id列合并
ORIGIN_DATA = DATA_DIR / "processed_df.jsonl"
origin_df = pd.read_json(ORIGIN_DATA, orient="records", lines=True)
processed_df.drop(columns=["name","fullDesc","status"], inplace=True)
df_merged = pd.merge(origin_df, processed_df, on="id", how="inner")
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 42 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4119 non-null   object
 1   name                  4119 non-null   object
 2   era                   3915 non-null   object
 3   culture               3594 non-null   object
 4   time                  4119 non-null   object
 5   dimensionsDesc        3744 non-null   object
 6   structuredDimensions  0 non-null      float64
 7   fullDesc              518 non-null    object
 8   features              0 non-null      float64
 9   excavationLocation    0 non-null      float64
 10  currentLocation       4119 non-null   object
 11  excavationDate        0 non-null      float64
 12  sourceCitation        4119 non-null   object
 13  collectionInfo        4119 non-null   object
 14  images                4119 non-null   object
 15  shape_type            3990 non-null   object
 16  categoryName          4119 non-null   object
 17  clickCounts           4119 non-null   int64
 18  collectedCounts       4119 non-null   int64
 19  collectionLevel       4110 non-null   float64
 20  collectionTexture     4017 non-null   object
 21  collectionUnit        4119 non-null   int64
 22  collectionsCategory   4119 non-null   int64
 23  fAudio                4119 non-null   object
 24  fVideo                0 non-null      float64
 25  image_count           4021 non-null   float64
 26  imgUrl                4093 non-null   object
 27  isHighQuality         4119 non-null   int64
 28  local_image_paths     3995 non-null   object
 29  museumName            4119 non-null   object
 30  pictureIds            4093 non-null   object
 31  threeUrl              14 non-null     object
 32  yearName              4119 non-null   object
 33  material              2842 non-null   object
 34  pattern               299 non-null    object
 35  shape                 2635 non-null   object
 36  state                 96 non-null     object
 37  color                 1208 non-null   object
 38  craft                 297 non-null    object
 39  raw_excavation_info   103 non-null    object
 40  raw_size_in_desc      82 non-null     object
 41  other_info            266 non-null    object
dtypes: float64(7), int64(5), object(30)
memory usage: 1.3+ MB

In [ ]:
from pprint import pprint
features = ['material', 'pattern', 'shape', 'state', 'color', 'craft',
       'raw_excavation_info', 'raw_size_in_desc', 'other_info']
for feature in features:
    print(f"{feature}的取值分布：")
    pprint(df_merged[feature].value_counts())
    print("\n")

In [ ]:
# 看一下raw_size_in_desc非空的行，对比这些行的raw_size_in_desc和dimensionsDesc的取值，观察相关性
size_vs_desc = df_merged[df_merged["raw_size_in_desc"].notna()][["id","name","fullDesc","raw_size_in_desc", "dimensionsDesc"]]
# 直接导出csv，对两边进行人工校准，再重新导入并覆盖

# 太麻烦了，开摆，不要弄这么复杂了，直接用dimensionsDesc提结构化尺寸信息

In [54]:
df_merged.head(5)

,id,name,era,culture,time,dimensionsDesc,structuredDimensions,fullDesc,features,excavationLocation,...,yearName,material,pattern,shape,state,color,craft,raw_excavation_info,raw_size_in_desc,other_info
0,003895c08aa84c2a98d3d1696db7ffcf,新石器时代大汶口文化红陶鋬盆,新石器时代,大汶口文化,"{'year': None, 'month': None, 'day': None}",口径19.2,NaN,夹砂红陶，侈口，上腹斜置，折腹后收为小平底，折腹处印压出一周斜点纹，鋬手由中腹弯出，端部窄薄上翘。,NaN,NaN,...,新石器时代,夹砂红陶,折腹处印压出一周斜点纹,侈口，上腹斜置，折腹后收为小平底，鋬手由中腹弯出，端部窄薄上翘,None,None,None,None,None,None
1,0043E78E1BCD4F11902DCA3C76607652,新石器时代大汶口文化褐陶鬶,新石器时代,大汶口文化,"{'year': None, 'month': None, 'day': None}",口径10.5厘米,NaN,None,NaN,NaN,...,新石器时代,褐陶,None,鬶,None,None,None,None,None,None
2,004658C82423474EB46AA00F6BEEDAFC,新石器时代大汶口文化红陶壶,新石器时代,大汶口文化,"{'year': None, 'month': None, 'day': None}",高*口径*底径：15.3*7.5*6.2,NaN,None,NaN,NaN,...,新石器时代,红陶,None,None,None,None,None,None,None,None
3,0053DF2D67D346059E75B0729A69FE5B,新石器时代夹砂黑陶碗,新石器时代,None,"{'year': None, 'month': None, 'day': None}",口径13，底径7，高5,NaN,None,NaN,NaN,...,新石器时代,夹砂黑陶,None,碗,None,黑陶,None,None,None,None
4,005C79C1C40F4AB9AA9183E5B383E158,新石器时代龙山文化陶褐鬹,新石器时代,龙山文化,"{'year': None, 'month': None, 'day': None}",通高*腹围*口径*流长：39.5*37*9.1*9.9,NaN,None,NaN,NaN,...,新石器时代,None,None,None,None,None,None,None,None,None

In [55]:
import pandas as pd

# 定义需要提取的属性列
feature_cols = ['material', 'pattern', 'shape', 'state', 'color', 'craft']

def build_features(row):
    features = []
    for col in feature_cols:
        val = row.get(col)
        # 过滤掉 NaN、None 以及空字符串
        if pd.notna(val) and str(val).strip() != '':
            features.append({
                "label": col,
                "value": str(val).strip()
            })
    # 如果全为空，可以选择返回空列表 [] 或 None，这里返回 [] 保持结构统一
    return features if features else []

# 批量应用到 features 列
df_merged['features'] = df_merged.apply(build_features, axis=1)

print("✅ features 列组装完毕！前 3 行预览：")
print(df_merged['features'].head(3).tolist())

✅ features 列组装完毕！前 3 行预览：
[[{'label': 'material', 'value': '夹砂红陶'}, {'label': 'pattern', 'value': '折腹处印压出一周斜点纹'}, {'label': 'shape', 'value': '侈口，上腹斜置，折腹后收为小平底，鋬手由中腹弯出，端部窄薄上翘'}], [{'label': 'material', 'value': '褐陶'}, {'label': 'shape', 'value': '鬶'}], [{'label': 'material', 'value': '红陶'}]]

In [ ]:
# 太累了，下面直接贴ai代码

In [57]:
import os
import json
import asyncio
import logging
from datetime import datetime
from pathlib import Path
import pandas as pd

# 必须执行此操作，否则在 Jupyter 中运行高并发 async 代码会引发 RuntimeError: This event loop is already running
import nest_asyncio
nest_asyncio.apply()

from dotenv import load_dotenv
from openai import AsyncOpenAI
from tqdm.asyncio import tqdm

# 1. 路径定义 (当前 Notebook 在 wwsdw.net/src 下)
BASE_DIR = Path.cwd().parent 
ENV_FILE = BASE_DIR / ".env"
OUTPUT_DIR = BASE_DIR / "data" / "extracted"
LOG_DIR = BASE_DIR / "log"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

# 2. 生成带时间戳的文件名
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
OUTPUT_FILE = OUTPUT_DIR / f"dimensions_{timestamp}.jsonl"
LOG_FILE = LOG_DIR / f"api_dimensions_{timestamp}.log"

# 3. 日志配置
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE, encoding="utf-8"),
        logging.StreamHandler()
    ]
)
logging.getLogger("httpx").setLevel(logging.WARNING)

# 4. 初始化大模型客户端
load_dotenv(ENV_FILE)
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
DEEPSEEK_BASE_URL = os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com/v1")

if not DEEPSEEK_API_KEY:
    raise ValueError(f"未找到 API KEY，请检查 {ENV_FILE}")

client = AsyncOpenAI(api_key=DEEPSEEK_API_KEY, base_url=DEEPSEEK_BASE_URL)

print("✅ 单元格 1 运行成功：环境、路径与日志配置完毕。")

✅ 单元格 1 运行成功：环境、路径与日志配置完毕。

In [58]:
# ==========================================
# 核心 Prompt 设计
# ==========================================
SYSTEM_PROMPT = """你是一个专业的考古数据结构化专家。
你的任务是将人类书写的、非结构化的文物尺寸描述，提取为结构化的 JSON 数组。

提取规则：
1. 你的返回必须是一个包含 "dimensions" 键的 JSON 对象，该键对应一个列表。
2. 列表中的每个对象必须严格包含以下 5 个字段：unit, value, deviation, range, label。
3. 如果未明确标明单位，默认 unit 为 "cm"。
4. 遇到类似 "直径*高=10*20" 的复合描述，请利用逻辑推理按顺序对应拆解：一个对象 label="直径", value=10.0；另一个对象 label="高度", value=20.0。
5. 对于区间值（如 "高10-15"），设置 value=null，range=[10.0, 15.0]。
6. 对于固定值加偏差（如 "口径10±0.1"），设置 value=10.0, deviation=0.1。
7. 空缺的数值字段请填 null。

输出格式示例：
{
  "dimensions": [
    {"unit": "cm", "value": 54.0, "deviation": null, "range": null, "label": "通高"},
    {"unit": "cm", "value": 37.0, "deviation": null, "range": null, "label": "口径"}
  ]
}
请严格输出 JSON，不要附加任何解释或 markdown 标记。"""

async def extract_dimension(item_id: str, desc: str, sem: asyncio.Semaphore, file_lock: asyncio.Lock):
    async with sem:
        try:
            response = await client.chat.completions.create(
                model="deepseek-chat",
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": f"提取以下尺寸描述:\n{desc}"}
                ],
                response_format={"type": "json_object"},
                temperature=0.1,
                timeout=45
            )
            
            extracted_json = json.loads(response.choices[0].message.content)
            result_data = {"id": item_id, "structuredDimensions": extracted_json.get("dimensions", [])}
            
            async with file_lock:
                with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
                    f.write(json.dumps(result_data, ensure_ascii=False) + "\n")
            
            logging.info(f"Success {item_id}")
            
        except Exception as e:
            logging.error(f"Failed {item_id}: {str(e)}")
            # 失败兜底，确保后续合并不会错位
            async with file_lock:
                with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
                    f.write(json.dumps({"id": item_id, "structuredDimensions": []}, ensure_ascii=False) + "\n")

async def run_extraction():
    # 筛选出有尺寸描述的行
    valid_mask = df_merged["dimensionsDesc"].notna() & (df_merged["dimensionsDesc"].str.strip() != "")
    tasks_data = df_merged[valid_mask][["id", "dimensionsDesc"]].to_dict("records")
    
    if not tasks_data:
        print("没有需要提取尺寸的数据！")
        return
        
    print(f"准备处理 {len(tasks_data)} 条尺寸数据...")
    sem = asyncio.Semaphore(20) # 控制并发为20
    file_lock = asyncio.Lock()
    
    tasks = [extract_dimension(row["id"], row["dimensionsDesc"], sem, file_lock) for row in tasks_data]
    await tqdm.gather(*tasks, desc="提取尺寸进度")
    print(f"\n✅ 所有请求完成！原始结果已存入: {OUTPUT_FILE}")

# 在 Jupyter 中直接 await 运行异步主函数
await run_extraction()

准备处理 3744 条尺寸数据...

提取尺寸进度:   0%|          | 0/3744 [00:00<?, ?it/s]2026-04-07 05:44:29,145 - INFO - Success 0806D214B6314CC887C471C6F6565310
提取尺寸进度:   0%|          | 1/3744 [00:02<2:17:44,  2.21s/it]2026-04-07 05:44:29,217 - INFO - Success 080647CB24DA4C8783EC62742E2B60FE
2026-04-07 05:44:29,221 - INFO - Success 525A71D96DB146C99D1D53672F7BE4C5
2026-04-07 05:44:29,232 - INFO - Success 334AD65BEC874925A2A06C604758B4BA
2026-04-07 05:44:29,291 - INFO - Success 9b10d234ef5b458388852a47d11cd8ee
提取尺寸进度:   0%|          | 5/3744 [00:02<22:26,  2.78it/s]  2026-04-07 05:44:29,422 - INFO - Success FC8806F3E8C04AD1B1132C6F38A224C8
2026-04-07 05:44:29,443 - INFO - Success 522A7D1C067C4F73BD94D0A3EABB294E
提取尺寸进度:   0%|          | 7/3744 [00:02<15:43,  3.96it/s]2026-04-07 05:44:29,722 - INFO - Success 333D1809472D4122AF4BAEFA39F58674
2026-04-07 05:44:29,742 - INFO - Success 7B4220D4A425489FA8948E86CAE34466
提取尺寸进度:   0%|          | 9/3744 [00:02<13:28,  4.62it/s]2026-04-07 05:44:29,751 - INFO - Success 332C16A376F84927B93DC4DCBCCB0A9F
2026-04-07 05:44:29,882 - INFO - Success CB433A75AFCD49A4983EC70E2B13C244
2026-04-07 05:44:29,884 - INFO - Success 5273BBCDD72C4876AF4C2BB97C62F03F
提取尺寸进度:   0%|          | 11/3744 [00:02<10:25,  5.96it/s]2026-04-07 05:44:29,912 - INFO - Success 080B3E145DC3460584E5C2E927105164
2026-04-07 05:44:29,921 - INFO - Success 7B1C44F8169A45C49F934CC12B9EC3E2
2026-04-07 05:44:30,320 - INFO - Success 7B1CF0F238414B11ACAF39A27979FB32
提取尺寸进度:   0%|          | 15/3744 [00:03<08:38,  7.19it/s]2026-04-07 05:44:30,323 - INFO - Success CB8242B88CF2437F87F3D97D9969B939
2026-04-07 05:44:30,329 - INFO - Success CB5FD05583A04BD3934C07F01F89F572
2026-04-07 05:44:30,350 - INFO - Success 9aeedd2e24ec48b09d0e1d1604144e5f
2026-04-07 05:44:30,363 - INFO - Success FBF939F29A9A43478B3A6CDFB45D00E7
2026-04-07 05:44:31,303 - INFO - Success 5283E382D6FD40A0B0F9C514140BB917
提取尺寸进度:   1%|          | 20/3744 [00:04<10:18,  6.02it/s]2026-04-07 05:44:31,309 - INFO - Success 9aee043390394b9ea5916928d7bd1acd
2026-04-07 05:44:31,501 - INFO - Success 9b2ea69a74e24b3aab14cdbe321112d3
提取尺寸进度:   1%|          | 22/3744 [00:04<09:25,  6.59it/s]2026-04-07 05:44:31,650 - INFO - Success 08421A5761FD44EF90DD20D46C435321
提取尺寸进度:   1%|          | 23/3744 [00:04<09:23,  6.60it/s]2026-04-07 05:44:31,745 - INFO - Success 3374BC62147645199BDFE4458008D571
2026-04-07 05:44:31,757 - INFO - Success FCCEFC11171B46DC858959F0E10D2D72
提取尺寸进度:   1%|          | 25/3744 [00:04<07:44,  8.01it/s]2026-04-07 05:44:31,830 - INFO - Success 52888FBF89B04E3E94B2039D54B85245
2026-04-07 05:44:31,870 - INFO - Success FCD14AD589D643F4B5756A2176E4A58B
提取尺寸进度:   1%|          | 27/3744 [00:04<06:33,  9.44it/s]2026-04-07 05:44:32,035 - INFO - Success 52918E13137E4A13A0758DC05E6A982F
2026-04-07 05:44:32,128 - INFO - Success 7B49C490EB934CB59A75F3ED893F2829
提取尺寸进度:   1%|          | 29/3744 [00:05<06:57,  8.90it/s]2026-04-07 05:44:32,132 - INFO - Success 33774550E4BA4A50AD09CEB5B7189DCB
2026-04-07 05:44:32,154 - INFO - Success CB8C01828A7E496C94D9DDEAA9A8CF6A
2026-04-07 05:44:32,269 - INFO - Success 7B4EE946B0734FE499806692B5CC9032
提取尺寸进度:   1%|          | 32/3744 [00:05<05:24, 11.43it/s]2026-04-07 05:44:32,342 - INFO - Success 0849950AF1924C4DB3E1905073AC33E7
2026-04-07 05:44:32,419 - INFO - Success 08374F25DAD6420DB6E1300E2AD056C8
提取尺寸进度:   1%|          | 34/3744 [00:05<05:12, 11.87it/s]2026-04-07 05:44:32,464 - INFO - Success 9b3350ceb73b44c685677e05e0b310cd
2026-04-07 05:44:32,467 - INFO - Success CB9C3CB47AC64C5A8B42C6A48CCAC03B
2026-04-07 05:44:32,738 - INFO - Success 7B65779D62ED44BC9213926FD7D8D4B7
提取尺寸进度:   1%|          | 37/3744 [00:05<05:41, 10.84it/s]2026-04-07 05:44:32,958 - INFO - Success FCD3125EB43D411F9D680ACDD170C4B0
2026-04-07 05:44:33,392 - INFO - Success 3388691f9829494495cbdbf9c59f0a8b
提取尺寸进度:   1%|          | 39/3744 [00:06<09:25,  6.56it/s]2026-04-07 05:44:33,485 - INFO - Success 3395308700B443DC9A39D159C12FEC38
2026-04-07 05:44:33,585 - INFO - Success CB9DD0C1156B4F218F2A0CDDA7FC47C3
提取尺寸进度:   1%|          | 41/3744 [00:06<08:29,  7.27it/s]2026-04-07 05:44:33,787 - INFO - Success 52B72408C1494F93829B46F749C54385
2026-04-07 05:44:33,800 - INFO - Success 084f7fb53c70404d968dac62dcdf8cb7
提取尺寸进度:   1%|          | 43/3744 [00:06<07:57,  7.74it/s]2026-04-07 05:44:33,874 - INFO - Success 9b537ed807fc486a85240970f4694a68
2026-04-07 05:44:34,032 - INFO - Success CBC68D82590944038BF097F92FF4E6EC
提取尺寸进度:   1%|          | 45/3744 [00:07<07:44,  7.97it/s]2026-04-07 05:44:34,066 - INFO - Success FCEEBE50B215455E9AADE3E2C7D37B04
2026-04-07 05:44:34,119 - INFO - Success 33AA5B6C5EF640FC859ED8B4967E3EAB
2026-04-07 05:44:34,128 - INFO - Success FD075872D8B74B7DA5B6656CB9F12511
2026-04-07 05:44:34,294 - INFO - Success 7B67DC1933F747F987920182133D0196
提取尺寸进度:   1%|▏         | 49/3744 [00:07<06:04, 10.14it/s]2026-04-07 05:44:34,357 - INFO - Success 9bd531452a2d4e3ebc88efab7313f336
2026-04-07 05:44:34,783 - INFO - Success 52F39A08EBC44F78BA110840B0538ADA
提取尺寸进度:   1%|▏         | 51/3744 [00:07<08:15,  7.46it/s]2026-04-07 05:44:34,802 - INFO - Success CBE78504265149F69D7349B6930201C7
2026-04-07 05:44:34,839 - INFO - Success 7B747A62BE874AD7B9CA2D17639347D7
2026-04-07 05:44:34,917 - INFO - Success 9be4a9ea64e64fa5aa98095655c75e0a
提取尺寸进度:   1%|▏         | 54/3744 [00:07<06:21,  9.66it/s]2026-04-07 05:44:34,931 - INFO - Success 085048143FF64BFE874251C3053CC1E8
2026-04-07 05:44:34,965 - INFO - Success FD25956223AF413D972DBD965A7CF86C
2026-04-07 05:44:35,106 - INFO - Success 0851018ACB3D45FC81A39B33B586BAE7
提取尺寸进度:   2%|▏         | 57/3744 [00:08<05:32, 11.10it/s]2026-04-07 05:44:35,399 - INFO - Success 9bf48c9cd617479f89aa2252f19e27fb
2026-04-07 05:44:35,410 - INFO - Success 5304d23b68a84e2a9f8e0bb7a643d6b9
提取尺寸进度:   2%|▏         | 59/3744 [00:08<06:26,  9.53it/s]2026-04-07 05:44:35,447 - INFO - Success 33AD5E93746A432DBC799D3FE09283CB
2026-04-07 05:44:35,593 - INFO - Success 7B8102BF623945A2BCB0C9E7D8223DAC
提取尺寸进度:   2%|▏         | 61/3744 [00:08<06:13,  9.85it/s]2026-04-07 05:44:35,636 - INFO - Success 33B15FD7262A416480168597890B83F6
2026-04-07 05:44:35,716 - INFO - Success FD4036DF999E46548717AC93C57255C8
提取尺寸进度:   2%|▏         | 63/3744 [00:08<05:34, 11.02it/s]2026-04-07 05:44:35,888 - INFO - Success CBEFFD38C10D4374AAC2BF5AEC6AA459
2026-04-07 05:44:36,312 - INFO - Success CBEF8CCDA1D44EE982EBDDD6CAA5C4E1
2026-04-07 05:44:36,314 - INFO - Success 533A3032AD3E463792E01F355231E977
2026-04-07 05:44:36,315 - INFO - Success 085578ED7FE04B70869BA1E24FEB8EB1
提取尺寸进度:   2%|▏         | 65/3744 [00:09<09:05,  6.75it/s]2026-04-07 05:44:36,683 - INFO - Success 7B815DF04CF54864B038A77E216DF702
提取尺寸进度:   2%|▏         | 68/3744 [00:09<08:30,  7.20it/s]2026-04-07 05:44:36,838 - INFO - Success 9d1ff4f7f01940eab82539c3fceecf72
提取尺寸进度:   2%|▏         | 69/3744 [00:09<08:39,  7.08it/s]2026-04-07 05:44:36,869 - INFO - Success CC06A562BA374A7A9FEE19128CF8F8B7
2026-04-07 05:44:37,044 - INFO - Success FD6B55F29F0140459AD3AC6CC435866C
提取尺寸进度:   2%|▏         | 71/3744 [00:10<07:56,  7.71it/s]2026-04-07 05:44:37,288 - INFO - Success 33C8ED8C784942B590A942199788B21F
提取尺寸进度:   2%|▏         | 72/3744 [00:10<09:10,  6.67it/s]2026-04-07 05:44:37,308 - INFO - Success 9c813e184ef74662860187fe5da3d74f
2026-04-07 05:44:37,448 - INFO - Success FD6C4E46620248C081CB4071007A7ACD
提取尺寸进度:   2%|▏         | 74/3744 [00:10<07:44,  7.90it/s]2026-04-07 05:44:37,477 - INFO - Success 5387A4B4641647FBBF1B8ED5EA5234CD
2026-04-07 05:44:37,627 - INFO - Success 5363B8A0165F49F691D98E7AC64846A2
提取尺寸进度:   2%|▏         | 76/3744 [00:10<07:00,  8.73it/s]2026-04-07 05:44:37,649 - INFO - Success CC0982530C3748F98ED2C7D8AF822801
2026-04-07 05:44:37,699 - INFO - Success 0856e42e089242f7a1f39762af355fde
2026-04-07 05:44:37,730 - INFO - Success 33CED0CAF1144F4F91235C6FC9BA05A9
提取尺寸进度:   2%|▏         | 79/3744 [00:10<04:58, 12.26it/s]2026-04-07 05:44:37,797 - INFO - Success 085E83D732784C9F935AA4082DED1137
2026-04-07 05:44:37,917 - INFO - Success FD7A73DFDA804133B57943EE8A004D8E
提取尺寸进度:   2%|▏         | 81/3744 [00:10<05:11, 11.76it/s]2026-04-07 05:44:37,968 - INFO - Success 5348744b000647da91e345d0c5cbf8d8
2026-04-07 05:44:38,043 - INFO - Success 0871BBE46EC7427EAE26AB4479ACC5BB
提取尺寸进度:   2%|▏         | 83/3744 [00:11<04:48, 12.71it/s]2026-04-07 05:44:38,052 - INFO - Success 7BADEA1BEFFC4B6394360131AC4A231E
2026-04-07 05:44:38,142 - INFO - Success 9d317ad78e1243a4ac6483d77bcab96f
2026-04-07 05:44:38,145 - INFO - Success 7B85570C1978416D8B38A162D0649BDC
提取尺寸进度:   2%|▏         | 86/3744 [00:11<03:45, 16.20it/s]2026-04-07 05:44:38,201 - INFO - Success 7BD9B22DB61A4485BBE40C325CAC3654
2026-04-07 05:44:38,404 - INFO - Success 33F748144D464B4EAF19697EC16DD03C
提取尺寸进度:   2%|▏         | 88/3744 [00:11<04:52, 12.52it/s]2026-04-07 05:44:38,982 - INFO - Success FDA256DBEA7848269C584A09C8F6F535
2026-04-07 05:44:39,259 - INFO - Success CC1323DD16D74095BDC135AB545E6A35
提取尺寸进度:   2%|▏         | 90/3744 [00:12<10:40,  5.70it/s]2026-04-07 05:44:39,444 - INFO - Success 53B67611F5524A3597B68856068DBDFF
2026-04-07 05:44:39,520 - INFO - Success 7BEA52B0CD7947F3AC40AE9CEED017C4
提取尺寸进度:   2%|▏         | 92/3744 [00:12<09:54,  6.14it/s]2026-04-07 05:44:39,538 - INFO - Success 9d6461a901a64cce9fe7792d98d8480c
2026-04-07 05:44:39,613 - INFO - Success CC209E9BD27544E1A7DF509FB83A8A17
2026-04-07 05:44:39,725 - INFO - Success 08CA1B457387429FA54C660050539B32
提取尺寸进度:   3%|▎         | 95/3744 [00:12<07:44,  7.86it/s]2026-04-07 05:44:39,739 - INFO - Success 08EBD8FE41BA4E37967DE2C73A3DBFFB
2026-04-07 05:44:39,766 - INFO - Success 33ed8eb9e3a54d3ab18a4fddcc045ae6
2026-04-07 05:44:39,867 - INFO - Success 9d6263993bdc4c46995dc1b5dfab5e0c
提取尺寸进度:   3%|▎         | 98/3744 [00:12<06:01, 10.09it/s]2026-04-07 05:44:40,121 - INFO - Success FDCC168F363948718A2CE3F614D8F810
2026-04-07 05:44:40,163 - INFO - Success FDA88B7F68E9401FA823BBC3C2F60C66
提取尺寸进度:   3%|▎         | 100/3744 [00:13<06:45,  8.98it/s]2026-04-07 05:44:40,320 - INFO - Success 9da2cc5a41484da995bc3811f1e94c7f
2026-04-07 05:44:40,401 - INFO - Success 53BEBF22CF74400D9121CD21472A64E0
提取尺寸进度:   3%|▎         | 102/3744 [00:13<06:53,  8.81it/s]2026-04-07 05:44:40,451 - INFO - Success CC2924C324A64428AF86093591B77A4E
2026-04-07 05:44:40,541 - INFO - Success 7BEFB183D00C48C4ADF19ED069893C38
提取尺寸进度:   3%|▎         | 104/3744 [00:13<06:09,  9.85it/s]2026-04-07 05:44:40,631 - INFO - Success 08EE1702BF8C4495B3C9A643A7CD5FC0
2026-04-07 05:44:40,633 - INFO - Success 340F8FA46C5E47CB8767F7D05EBD3D37
2026-04-07 05:44:40,701 - INFO - Success 342168d7d1ec407db03f032acf040d14
提取尺寸进度:   3%|▎         | 107/3744 [00:13<05:04, 11.93it/s]2026-04-07 05:44:40,931 - INFO - Success 53CA0EAD13024275A8A92896B2F93F35
2026-04-07 05:44:40,951 - INFO - Success CC485CCF818049F6A7938A4F6C4B4E1C
提取尺寸进度:   3%|▎         | 109/3744 [00:14<05:43, 10.58it/s]2026-04-07 05:44:41,311 - INFO - Success 9dbffd2582464ae79b34b9a40549dcb2
2026-04-07 05:44:41,841 - INFO - Success 53CC2A99197A4EBE9151966457183026
提取尺寸进度:   3%|▎         | 111/3744 [00:14<11:28,  5.28it/s]2026-04-07 05:44:42,051 - INFO - Success 3437E7E6A07F427CAF0E5DAB9D94831D
提取尺寸进度:   3%|▎         | 112/3744 [00:15<11:40,  5.19it/s]2026-04-07 05:44:42,121 - INFO - Success 342BA96488844615B162F1059968A77A
2026-04-07 05:44:42,251 - INFO - Success FDCDF586649B4433B5502623FF0DE762
提取尺寸进度:   3%|▎         | 114/3744 [00:15<09:53,  6.12it/s]2026-04-07 05:44:42,289 - INFO - Success 08ee715ec0aa4cafa1e60b59718e4aa1
2026-04-07 05:44:42,313 - INFO - Success 7BFD59D8C300446C9636FAE4D4E4A438
2026-04-07 05:44:42,361 - INFO - Success 53E70927A1F242B68F67E45C750E9208
提取尺寸进度:   3%|▎         | 117/3744 [00:15<06:46,  8.92it/s]2026-04-07 05:44:42,421 - INFO - Success CC52CFF70D9F45C38C8606EF3F3A65A6
2026-04-07 05:44:42,463 - INFO - Success 9e2a1f0a1f8d4e4a8321b2c03dac4c59
提取尺寸进度:   3%|▎         | 119/3744 [00:15<05:44, 10.51it/s]2026-04-07 05:44:42,677 - INFO - Success CC6C420DD8D24C09A7F6ED28C062EB92
2026-04-07 05:44:42,715 - INFO - Success 7BF1DC6C0540411A8913B96127BDD74F
提取尺寸进度:   3%|▎         | 121/3744 [00:15<06:16,  9.63it/s]2026-04-07 05:44:42,951 - INFO - Success 53E50295734E48A98F6E6EF41EB41589
2026-04-07 05:44:42,966 - INFO - Success 9e075501d67d437c9eab2e54e8e62cb0
提取尺寸进度:   3%|▎         | 123/3744 [00:16<06:38,  9.08it/s]2026-04-07 05:44:43,063 - INFO - Success 7C3E98C1658448829F25E2EF87809CC8
2026-04-07 05:44:43,148 - INFO - Success 08fb4aa79f884e46a510619894361cf7
提取尺寸进度:   3%|▎         | 125/3744 [00:16<06:18,  9.56it/s]2026-04-07 05:44:43,205 - INFO - Success 08fc259c29e64d49b37a653b0a17e1c7
2026-04-07 05:44:43,303 - INFO - Success FDDF0AC29B064D9DBC3FF4E9BF58419C
提取尺寸进度:   3%|▎         | 127/3744 [00:16<05:49, 10.34it/s]2026-04-07 05:44:43,469 - INFO - Success 3443A62CAA064AC29222FAC31E30A482
2026-04-07 05:44:43,666 - INFO - Success FDFECE8283254BBE89BF3527462EA45F
提取尺寸进度:   3%|▎         | 129/3744 [00:16<07:19,  8.22it/s]2026-04-07 05:44:43,828 - INFO - Success 7C41A17A1BE14168A786A5B7E1D9DF88
2026-04-07 05:44:43,951 - INFO - Success 53F9628EB0544DB488E51E280FFDC5C5
提取尺寸进度:   3%|▎         | 131/3744 [00:17<07:42,  7.81it/s]2026-04-07 05:44:44,033 - INFO - Success FE02BB21B44C4FB5A3B660FC6A0D0C3C
2026-04-07 05:44:44,115 - INFO - Success 345613A67DC84A22B0A0840882C2021E
提取尺寸进度:   4%|▎         | 133/3744 [00:17<06:52,  8.75it/s]2026-04-07 05:44:44,120 - INFO - Success 09122F2485FB463E9CD6BF3F4C454DCB
2026-04-07 05:44:44,253 - INFO - Success CC7CA52C649D4B4FB134F06E9C5BF934
提取尺寸进度:   4%|▎         | 135/3744 [00:17<06:03,  9.92it/s]2026-04-07 05:44:44,615 - INFO - Success CC84A0A0EC0D47D5A41472D8BB68F944
2026-04-07 05:44:44,921 - INFO - Success 9e48f6cbe0a84caf80f8d3f85e941307
提取尺寸进度:   4%|▎         | 137/3744 [00:17<10:14,  5.87it/s]2026-04-07 05:44:44,938 - INFO - Success 54076A554F924FA6B203D48638278D2E
2026-04-07 05:44:44,966 - INFO - Success 3457F2B143904F87B707FA91EF13DED7
2026-04-07 05:44:44,974 - INFO - Success 9e79ea39f8d549d982ef7c6cb0b6417f
2026-04-07 05:44:45,006 - INFO - Success 7C6973A3F3A142A68AFE91316DAE8F1F
2026-04-07 05:44:45,030 - INFO - Success 095CF4A0B0164F2592F66B90E142D3FE
提取尺寸进度:   4%|▍         | 142/3744 [00:18<05:37, 10.67it/s]2026-04-07 05:44:45,145 - INFO - Success 9e3ba55ccf6e49e496c70decf1abeb7b
2026-04-07 05:44:45,216 - INFO - Success FE319B2F11AF4EEA88EDB1F08211293E
提取尺寸进度:   4%|▍         | 144/3744 [00:18<05:36, 10.69it/s]2026-04-07 05:44:45,369 - INFO - Success 092115335F864413A639A634EC47E9CE
2026-04-07 05:44:45,689 - INFO - Success 345C3D2E85474A7996673E19DC0C3ADB
提取尺寸进度:   4%|▍         | 146/3744 [00:18<07:43,  7.77it/s]2026-04-07 05:44:45,744 - INFO - Success CCB3DDB1D84447F7872FDE90B034C012
2026-04-07 05:44:45,799 - INFO - Success 54077D1FE0634A3C8A5AE5F40CA46FFB
提取尺寸进度:   4%|▍         | 148/3744 [00:18<06:33,  9.13it/s]2026-04-07 05:44:45,804 - INFO - Success 9e855dda2e524478babce6e985b24d0b
2026-04-07 05:44:46,088 - INFO - Success 7C7D8F70037440A9ADF2A13F6F6DE35D
提取尺寸进度:   4%|▍         | 150/3744 [00:19<07:07,  8.40it/s]2026-04-07 05:44:46,092 - INFO - Success FE6A502FB94247F7A7E34EED42572F17
2026-04-07 05:44:46,282 - INFO - Success 54253223dfa4494cbc3d61d3423ad38a
2026-04-07 05:44:46,284 - INFO - Success FE722FA1E36F431298A3A73D6BA29964
提取尺寸进度:   4%|▍         | 152/3744 [00:19<06:45,  8.85it/s]2026-04-07 05:44:46,451 - INFO - Success 7C97A157BDCE4DB2AAA29F8A8C4C69A9
提取尺寸进度:   4%|▍         | 154/3744 [00:19<06:15,  9.55it/s]2026-04-07 05:44:46,822 - INFO - Success 095F0098BC704C9A9384D7FB54CA91B6
2026-04-07 05:44:46,981 - INFO - Success 3463EBDE864F428F8A6C78F9E6C00957
提取尺寸进度:   4%|▍         | 156/3744 [00:20<09:02,  6.62it/s]2026-04-07 05:44:47,021 - INFO - Success 5428585C0FDC44DEADBD3A5E4734B11E
2026-04-07 05:44:47,041 - INFO - Success CCEDD530DDC049FB94083B4A8CD4497B
2026-04-07 05:44:47,121 - INFO - Success 9f4b25d58c4f4974b148e626bb1c6c3a
提取尺寸进度:   4%|▍         | 159/3744 [00:20<06:38,  9.00it/s]2026-04-07 05:44:47,351 - INFO - Success 0963CA91C21447539EBED82F62901CE5
2026-04-07 05:44:47,432 - INFO - Success 7C9DFDE821364AA7BEF69C7946005055
提取尺寸进度:   4%|▍         | 161/3744 [00:20<07:20,  8.14it/s]2026-04-07 05:44:47,471 - INFO - Success FE76713806534C1DA9F37131FEE0DF53
2026-04-07 05:44:47,612 - INFO - Success CD05BD1DE800438CBE80500C3CF190B2
提取尺寸进度:   4%|▍         | 163/3744 [00:20<06:47,  8.79it/s]2026-04-07 05:44:47,652 - INFO - Success 3460D619AC544F4EAA24DC81121E3306
2026-04-07 05:44:47,661 - INFO - Success 7CC24FA37E3147A8ACB35809CBF345E2
2026-04-07 05:44:47,663 - INFO - Success 0961ACD546204D10AFF12F8FE4750774
2026-04-07 05:44:47,881 - INFO - Success CD2BDD1A3DBA4467AD694B6ED388D9DF
提取尺寸进度:   4%|▍         | 167/3744 [00:20<05:33, 10.72it/s]2026-04-07 05:44:47,921 - INFO - Success 542DCCF9B6B944CEACB36E66881BCA7B
2026-04-07 05:44:47,942 - INFO - Success 3472C273806A43789760B50841E5017E
2026-04-07 05:44:48,032 - INFO - Success CD18DB205DF34984B9C11389D12855E4
提取尺寸进度:   5%|▍         | 170/3744 [00:21<04:44, 12.58it/s]2026-04-07 05:44:48,151 - INFO - Success FE7D7925B52A4C7F8AFDED9F6EC8EA63
2026-04-07 05:44:48,441 - INFO - Success A001D83B68574BCBA5C3266A95125BEF
提取尺寸进度:   5%|▍         | 172/3744 [00:21<06:28,  9.19it/s]2026-04-07 05:44:48,758 - INFO - Success 7CD4DD0E2A904321A60006C35643D301
2026-04-07 05:44:48,853 - INFO - Success 9ff294b8485c4304a463faa25b4448b9
提取尺寸进度:   5%|▍         | 174/3744 [00:21<07:55,  7.51it/s]2026-04-07 05:44:49,038 - INFO - Success 7CFB38D3F02C4C57BA9852443A96C0E9
提取尺寸进度:   5%|▍         | 175/3744 [00:22<08:23,  7.09it/s]2026-04-07 05:44:49,087 - INFO - Success FE9136269ADC4575AED29AA6570F7DC4
2026-04-07 05:44:49,264 - INFO - Success 7CE34FE74D3D41ACADF1739BF450F2FC
提取尺寸进度:   5%|▍         | 177/3744 [00:22<07:52,  7.55it/s]2026-04-07 05:44:49,471 - INFO - Success 3491ED6E257A408D8EF4D9D9214FB71F
提取尺寸进度:   5%|▍         | 178/3744 [00:22<08:39,  6.86it/s]2026-04-07 05:44:49,489 - INFO - Success 09662EB7F9D54BF0BBC8B9F426BDC0E0
2026-04-07 05:44:49,708 - INFO - Success A02E0C54881B48B191061AFC96585BAD
提取尺寸进度:   5%|▍         | 180/3744 [00:22<08:07,  7.32it/s]2026-04-07 05:44:49,734 - INFO - Success A005E16CD9154F0ABD86EEFD3F6F13B8
2026-04-07 05:44:49,809 - INFO - Success 543E64285F2B4358AC01C25B62E2FF93
提取尺寸进度:   5%|▍         | 182/3744 [00:22<06:26,  9.21it/s]2026-04-07 05:44:49,916 - INFO - Success CD393101819442A38DDE24840E5A8A84
2026-04-07 05:44:49,971 - INFO - Success FEB375EF7AC94F1D9362A6F0AD4A3D88
提取尺寸进度:   5%|▍         | 184/3744 [00:23<05:55, 10.02it/s]2026-04-07 05:44:50,031 - INFO - Success 096c1dcf8ec848c6ab199b20d63cabdc
2026-04-07 05:44:50,159 - INFO - Success 545DFB418CC9449DBE57C1C947BFD47D
提取尺寸进度:   5%|▍         | 186/3744 [00:23<05:49, 10.19it/s]2026-04-07 05:44:50,196 - INFO - Success 34B814207054463B9D3315988BEBBDAA
2026-04-07 05:44:50,278 - INFO - Success CD39805727714C0B848A86F43EF53B2B
提取尺寸进度:   5%|▌         | 188/3744 [00:23<05:06, 11.61it/s]2026-04-07 05:44:50,468 - INFO - Success 099A0C1FBBD945BF8302448F6A52C9E1
2026-04-07 05:44:50,506 - INFO - Success 546D68C0F992422BB918CA721337AFD6
提取尺寸进度:   5%|▌         | 190/3744 [00:23<05:36, 10.55it/s]2026-04-07 05:44:50,530 - INFO - Success 34B9ED62C08C43CD94ED61B2618ED13A
2026-04-07 05:44:50,561 - INFO - Success FED885FBB5114E31B55B35C78370C51C
2026-04-07 05:44:50,734 - INFO - Success A074966A554A4DAFBDF35EAA9331930B
提取尺寸进度:   5%|▌         | 193/3744 [00:23<05:10, 11.44it/s]2026-04-07 05:44:51,073 - INFO - Success CD39D6A24EF34F3092F7BD9C5169C823
2026-04-07 05:44:51,260 - INFO - Success 7D2BF8CB2F0341A2992B3A11155B8E06
提取尺寸进度:   5%|▌         | 195/3744 [00:24<08:00,  7.39it/s]2026-04-07 05:44:51,479 - INFO - Success 546FE17ED6F147218EF8B6C7A091904D
提取尺寸进度:   5%|▌         | 196/3744 [00:24<08:49,  6.71it/s]2026-04-07 05:44:51,606 - INFO - Success FEE2BB85964A43FAAF00865110816152
提取尺寸进度:   5%|▌         | 197/3744 [00:24<08:33,  6.91it/s]2026-04-07 05:44:51,671 - INFO - Success CD44628DC5AD418E90430A96AE731E4E
2026-04-07 05:44:51,725 - INFO - Success 09AB673F81644B71A696D4A3D57C410A

✅ 所有请求完成！原始结果已存入: d:\LocalWorkSpace\20260202_museum_data_crawling\wwsdw.net\data\extracted\dimensions_20260407_054332.jsonl

In [59]:
# 读取提取的 JSONL 结果
extracted_dims = []
with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
    for line in f:
        if line.strip():
            extracted_dims.append(json.loads(line))

# 转为 DataFrame
df_dims = pd.DataFrame(extracted_dims)

# 如果你的 df_merged 原本没有 structuredDimensions 列，先初始化
if "structuredDimensions" not in df_merged.columns:
    df_merged["structuredDimensions"] = None

# 通过 id 进行更新合并
# 使用 set_index 确保对齐准确，避免产生重复行或乱序
df_merged.set_index("id", inplace=True)
df_dims.set_index("id", inplace=True)

# 将提取到的 structuredDimensions 赋值回主 df
df_merged["structuredDimensions"].update(df_dims["structuredDimensions"])

# 恢复 id 为普通列
df_merged.reset_index(inplace=True)
df_dims.reset_index(inplace=True)

print("✅ 结构化尺寸已成功合并至 df_merged 的 structuredDimensions 列！")
print("你可以运行 df_merged[['dimensionsDesc', 'structuredDimensions']].dropna(subset=['dimensionsDesc']).head() 来查看效果。")

✅ 结构化尺寸已成功合并至 df_merged 的 structuredDimensions 列！
你可以运行 df_merged[['dimensionsDesc', 'structuredDimensions']].dropna(subset=['dimensionsDesc']).head() 来查看效果。

C:\Users\NOVA\AppData\Local\Temp\ipykernel_11804\971752797.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_merged["structuredDimensions"].update(df_dims["structuredDimensions"])
C:\Users\NOVA\AppData\Local\Temp\ipykernel_11804\971752797.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[list([{'unit': 'cm', 'value': 19.2, 'deviation': None, 'range': None, 'label': '口径'}])
 list([{'unit': 'cm', 'value': 10.5, 'deviation': None, 'range': None, 'label': '口径'}])
 list([{'unit': 'cm', 'value': 15.3, 'deviation': None, 'range': None, 'label': '高度'}, {'unit': 'cm', 'value': 7.5, 'deviation': None, 'range': None, 'label': '口径'}, {'unit': 'cm', 'value': 6.2, 'deviation': None, 'range': None, 'label': '底径'}])
 ...
 list([{'unit': 'cm', 'value': 9.8, 'deviation': None, 'range': None, 'label': '高度'}, {'unit': 'cm', 'value': 20.6, 'deviation': None, 'range': None, 'label': '口径'}, {'unit': 'cm', 'value': 4.0, 'deviation': None, 'range': None, 'label': '足高'}, {'unit': 'cm', 'value': 13.9, 'deviation': None, 'range': None, 'label': '底径'}])
 list([{'unit': 'cm', 'value': 17.2, 'deviation': None, 'range': None, 'label': '口径'}, {'unit': 'cm', 'value': 8.1, 'deviation': None, 'range': None, 'label': '高度'}])
 list([{'unit': 'cm', 'value': 7.1, 'deviation': None, 'range': None, 'label': '高度'}, {'unit': 'cm', 'value': 18.9, 'deviation': None, 'range': None, 'label': '口径'}, {'unit': 'cm', 'value': 6.2, 'deviation': None, 'range': None, 'label': '底径'}, {'unit': 'cm', 'value': 16.6, 'deviation': None, 'range': None, 'label': '腹径'}])]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_merged["structuredDimensions"].update(df_dims["structuredDimensions"])

In [60]:
df_merged.head(5)

,id,name,era,culture,time,dimensionsDesc,structuredDimensions,fullDesc,features,excavationLocation,...,yearName,material,pattern,shape,state,color,craft,raw_excavation_info,raw_size_in_desc,other_info
0,003895c08aa84c2a98d3d1696db7ffcf,新石器时代大汶口文化红陶鋬盆,新石器时代,大汶口文化,"{'year': None, 'month': None, 'day': None}",口径19.2,"[{'unit': 'cm', 'value': 19.2, 'deviation': No...",夹砂红陶，侈口，上腹斜置，折腹后收为小平底，折腹处印压出一周斜点纹，鋬手由中腹弯出，端部窄薄上翘。,"[{'label': 'material', 'value': '夹砂红陶'}, {'lab...",NaN,...,新石器时代,夹砂红陶,折腹处印压出一周斜点纹,侈口，上腹斜置，折腹后收为小平底，鋬手由中腹弯出，端部窄薄上翘,None,None,None,None,None,None
1,0043E78E1BCD4F11902DCA3C76607652,新石器时代大汶口文化褐陶鬶,新石器时代,大汶口文化,"{'year': None, 'month': None, 'day': None}",口径10.5厘米,"[{'unit': 'cm', 'value': 10.5, 'deviation': No...",None,"[{'label': 'material', 'value': '褐陶'}, {'label...",NaN,...,新石器时代,褐陶,None,鬶,None,None,None,None,None,None
2,004658C82423474EB46AA00F6BEEDAFC,新石器时代大汶口文化红陶壶,新石器时代,大汶口文化,"{'year': None, 'month': None, 'day': None}",高*口径*底径：15.3*7.5*6.2,"[{'unit': 'cm', 'value': 15.3, 'deviation': No...",None,"[{'label': 'material', 'value': '红陶'}]",NaN,...,新石器时代,红陶,None,None,None,None,None,None,None,None
3,0053DF2D67D346059E75B0729A69FE5B,新石器时代夹砂黑陶碗,新石器时代,None,"{'year': None, 'month': None, 'day': None}",口径13，底径7，高5,"[{'unit': 'cm', 'value': 13.0, 'deviation': No...",None,"[{'label': 'material', 'value': '夹砂黑陶'}, {'lab...",NaN,...,新石器时代,夹砂黑陶,None,碗,None,黑陶,None,None,None,None
4,005C79C1C40F4AB9AA9183E5B383E158,新石器时代龙山文化陶褐鬹,新石器时代,龙山文化,"{'year': None, 'month': None, 'day': None}",通高*腹围*口径*流长：39.5*37*9.1*9.9,"[{'unit': 'cm', 'value': 39.5, 'deviation': No...",None,[],NaN,...,新石器时代,None,None,None,None,None,None,None,None,None

In [61]:
import json
import asyncio
import logging
from datetime import datetime
import pandas as pd
from tqdm.asyncio import tqdm

# ==========================================
# 1. 强制空值打底（满足无信息直接全填 null 的要求）
# ==========================================
default_location = {"country": None, "province": None, "city": None, "district": None, "specificAddress": None, "coordinate": None}
default_date = {"year": None, "month": None, "day": None}

# 如果原表没有这两列，或者需要覆写，直接全量初始化为默认字典
df_merged["excavationLocation"] = [default_location.copy() for _ in range(len(df_merged))]
df_merged["excavationDate"] = [default_date.copy() for _ in range(len(df_merged))]

# ==========================================
# 2. 路径与日志配置 (沿用之前的 BASE_DIR)
# ==========================================
timestamp_exc = datetime.now().strftime("%Y%m%d_%H%M%S")
OUTPUT_EXC_FILE = OUTPUT_DIR / f"excavation_{timestamp_exc}.jsonl"
LOG_EXC_FILE = LOG_DIR / f"api_excavation_{timestamp_exc}.log"

# 单独为出土信息开一个 FileHandler 记录日志
exc_logger = logging.getLogger("excavation")
exc_logger.setLevel(logging.INFO)
exc_handler = logging.FileHandler(LOG_EXC_FILE, encoding="utf-8")
exc_handler.setFormatter(logging.Formatter("%(asctime)s - %(levelname)s - %(message)s"))
exc_logger.addHandler(exc_handler)

# ==========================================
# 3. 提示词与提取逻辑
# ==========================================
SYSTEM_PROMPT_EXC = """你是一个专业的考古信息结构化提取助手。
请从用户提供的出土信息原始文本中，提取出土地点和出土日期，并严格按照 JSON 格式输出。

输出必须包含两个键："excavationLocation" 和 "excavationDate"，具体结构如下：
{
  "excavationLocation": {
    "country": "提取的国家，如无填 null",
    "province": "提取的省份，如无填 null",
    "city": "提取的城市，如无填 null",
    "district": "提取的区县，如无填 null",
    "specificAddress": "提取的具体遗址或地址，如无填 null",
    "coordinate": null
  },
  "excavationDate": {
    "year": "提取的年份(纯数字字符串或带'年'均可)，如无填 null",
    "month": "提取的月份，如无填 null",
    "day": "提取的日期，如无填 null"
  }
}
要求：
1. 只能依靠提供的文本进行提取，不知道的字段一律填 null。
2. 严格输出合法的 JSON 对象，不加任何 Markdown 标记。"""

async def extract_excavation(item_id: str, desc: str, sem: asyncio.Semaphore, file_lock: asyncio.Lock):
    async with sem:
        try:
            response = await client.chat.completions.create(
                model="deepseek-chat",
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT_EXC},
                    {"role": "user", "content": f"提取以下出土信息文本:\n{desc}"}
                ],
                response_format={"type": "json_object"},
                temperature=0.1,
                timeout=45
            )
            
            extracted_json = json.loads(response.choices[0].message.content)
            
            # 增加鲁棒性，防止模型漏掉主键
            result_data = {
                "id": item_id,
                "excavationLocation": extracted_json.get("excavationLocation", default_location),
                "excavationDate": extracted_json.get("excavationDate", default_date)
            }
            
            async with file_lock:
                with open(OUTPUT_EXC_FILE, "a", encoding="utf-8") as f:
                    f.write(json.dumps(result_data, ensure_ascii=False) + "\n")
            
            exc_logger.info(f"Success {item_id}")
            
        except Exception as e:
            exc_logger.error(f"Failed {item_id}: {str(e)}")
            # 失败兜底
            async with file_lock:
                with open(OUTPUT_EXC_FILE, "a", encoding="utf-8") as f:
                    f.write(json.dumps({"id": item_id, "excavationLocation": default_location, "excavationDate": default_date}, ensure_ascii=False) + "\n")

async def run_excavation_extraction():
    # 仅筛选出 raw_excavation_info 不为空的行
    valid_mask = df_merged["raw_excavation_info"].notna() & (df_merged["raw_excavation_info"].str.strip() != "")
    tasks_data = df_merged[valid_mask][["id", "raw_excavation_info"]].to_dict("records")
    
    if not tasks_data:
        print("没有需要提取的出土信息！所有数据已默认打底为 null。")
        return
        
    print(f"准备处理 {len(tasks_data)} 条出土信息数据...")
    sem = asyncio.Semaphore(20)
    file_lock = asyncio.Lock()
    
    tasks = [extract_excavation(row["id"], row["raw_excavation_info"], sem, file_lock) for row in tasks_data]
    await tqdm.gather(*tasks, desc="出土信息提取进度")
    print(f"\n✅ 所有出土信息提取完成！原始结果已存入: {OUTPUT_EXC_FILE}")

# 执行提取
await run_excavation_extraction()

准备处理 103 条出土信息数据...

出土信息提取进度:   0%|          | 0/103 [00:00<?, ?it/s]2026-04-07 06:02:55,981 - INFO - Success 3700000201862104C100420145113484
出土信息提取进度:   1%|          | 1/103 [00:02<04:02,  2.38s/it]2026-04-07 06:02:56,010 - INFO - Success CD05BD1DE800438CBE80500C3CF190B2
2026-04-07 06:02:56,021 - INFO - Success E37C9F919A2B4AE3AC9B145B29288D5D
2026-04-07 06:02:56,099 - INFO - Success 3700000201862104B100425094809093
出土信息提取进度:   4%|▍         | 4/103 [00:02<00:47,  2.07it/s]2026-04-07 06:02:56,133 - INFO - Success 3700000201862104C100420182423406
2026-04-07 06:02:56,157 - INFO - Success 3700000201862104B100424111031924
2026-04-07 06:02:56,178 - INFO - Success 3700000201862104C100425092600484
2026-04-07 06:02:56,223 - INFO - Success 06b6eb96528a4fe68887b0658eeaaf78
出土信息提取进度:   8%|▊         | 8/103 [00:02<00:19,  4.80it/s]2026-04-07 06:02:56,232 - INFO - Success 0FF15D85DEE4496C935EA878318BA2D5
2026-04-07 06:02:56,240 - INFO - Success 07b866fcbb5547bd80a464f74fa0fbc0
2026-04-07 06:02:56,255 - INFO - Success 01210ea5cbb14a6ea6de870299758873
2026-04-07 06:02:56,265 - INFO - Success 3700000201862104B100426155857937
2026-04-07 06:02:56,268 - INFO - Success D3F6F20E44AD4A79A3E81C2FEA348DCE
2026-04-07 06:02:56,270 - INFO - Success 0C1D1E0DA1424A318CA9DC8A4139FBBD
2026-04-07 06:02:56,309 - INFO - Success 0706381701a34e0ca5ff8bc75a9428a9
2026-04-07 06:02:56,314 - INFO - Success DBAC2EB7D1944B8B9821F9B55A8F5CDB
2026-04-07 06:02:56,342 - INFO - Success E34CFE29F9574A59ADFFBB95EC0ED2CB
出土信息提取进度:  17%|█▋        | 17/103 [00:02<00:06, 12.61it/s]2026-04-07 06:02:56,348 - INFO - Success D9553EDA8DEF4A8E8AD5CEB8DD17455C
2026-04-07 06:02:56,372 - INFO - Success 063f04237365413588b166fadfa28e1c
2026-04-07 06:02:56,381 - INFO - Success 09053083EC594D80BF074EBF18C9994B
2026-04-07 06:02:58,344 - INFO - Success 0e17c26e26d4481c80697ebb7fff3a28
2026-04-07 06:02:58,381 - INFO - Success 4024bec8d93741cb902dc5f3804e221e
出土信息提取进度:  21%|██▏       | 22/103 [00:04<00:15,  5.20it/s]2026-04-07 06:02:58,533 - INFO - Success 4359f2f7976c40dca101745c5eefdd91
2026-04-07 06:02:58,555 - INFO - Success F5B4B9179C6841B3ADC3AFCF0CEF1289
2026-04-07 06:02:58,558 - INFO - Success a220533e828e4959a6ebbc719c7e7250
出土信息提取进度:  24%|██▍       | 25/103 [00:04<00:12,  6.17it/s]2026-04-07 06:02:58,569 - INFO - Success 1627658f556943669ba466d9ba0c442f
2026-04-07 06:02:58,632 - INFO - Success a188d5fb36d64ccca210d8fa758dade1
2026-04-07 06:02:58,666 - INFO - Success bc364728c1884104868da57ccb91c35a
出土信息提取进度:  27%|██▋       | 28/103 [00:05<00:09,  7.63it/s]2026-04-07 06:02:58,670 - INFO - Success F61A6FF4E3374644BA01D4103712C711
2026-04-07 06:02:58,730 - INFO - Success 0ed8ec95633f4f9db2f818f0360a9cb7
2026-04-07 06:02:58,764 - INFO - Success 120c1080a3474813b86cda06a26d149e
2026-04-07 06:02:58,777 - INFO - Success 43bef139edeb44f4845b2e869576df1d
出土信息提取进度:  31%|███       | 32/103 [00:05<00:06, 10.19it/s]2026-04-07 06:02:58,787 - INFO - Success 43976A55AF614ED4AF0A5DF99BAB3CF6
2026-04-07 06:02:58,800 - INFO - Success 198ea275d7ce47d388109f1dd7d846d2
2026-04-07 06:02:59,244 - INFO - Success 13314acfb91a4e87bf5cd98ae5fc25f2
2026-04-07 06:02:59,247 - INFO - Success b2d80f6f101c46c1b01725edd1375eb3
2026-04-07 06:02:59,248 - INFO - Success 176feb66f389486f8e7c268fc7c14e60
出土信息提取进度:  34%|███▍      | 35/103 [00:05<00:07,  8.85it/s]2026-04-07 06:02:59,266 - INFO - Success 4d62f8be240f42e198234b73c53a8ec0
2026-04-07 06:02:59,409 - INFO - Success a814f8dbbab04f76a157f70ecfd27c47
出土信息提取进度:  38%|███▊      | 39/103 [00:05<00:05, 11.18it/s]2026-04-07 06:02:59,463 - INFO - Success 4C93BBE279074E588FA757E5F91C07C3
2026-04-07 06:03:00,793 - INFO - Success 5348744b000647da91e345d0c5cbf8d8
2026-04-07 06:03:00,818 - INFO - Success 1bcc5dabea99421caf71df2c13af4453
出土信息提取进度:  41%|████      | 42/103 [00:07<00:11,  5.32it/s]2026-04-07 06:03:00,961 - INFO - Success 1e38b43503e54ac1bb86c12281e45ae8
2026-04-07 06:03:00,964 - INFO - Success c63903fe68f344b490a66739058de72a
出土信息提取进度:  43%|████▎     | 44/103 [00:07<00:09,  6.05it/s]2026-04-07 06:03:01,022 - INFO - Success 2258f5814eda4d0296ee402e58a9482b
2026-04-07 06:03:01,068 - INFO - Success 56b91553ccaf4e65a63770c606593478
出土信息提取进度:  45%|████▍     | 46/103 [00:07<00:07,  7.13it/s]2026-04-07 06:03:01,115 - INFO - Success 5fff92b612a74a989f9ec4228e8ef710
2026-04-07 06:03:01,120 - INFO - Success 5893EB0B327A47A3A045B5593C2D212F
2026-04-07 06:03:01,298 - INFO - Success bfcb68654d18476bb53a7530d3452e71
出土信息提取进度:  48%|████▊     | 49/103 [00:07<00:06,  8.35it/s]2026-04-07 06:03:01,517 - INFO - Success 22508998539e4fb8bbab10cf56e8c131
2026-04-07 06:03:01,565 - INFO - Success 2a2e86dda4c843d4803bfc0a710ad276
出土信息提取进度:  50%|████▉     | 51/103 [00:07<00:06,  8.13it/s]2026-04-07 06:03:01,610 - INFO - Success 1cb2b57025a5482da698e3c082d3aa14
2026-04-07 06:03:01,621 - INFO - Success e6897cb4c55047dfb19f5d88dff01a2e
2026-04-07 06:03:01,655 - INFO - Success e0139910734c405882c87bac96d47920
2026-04-07 06:03:01,658 - INFO - Success 59b2cf50d43545a8ae12e263cf4a6a35
2026-04-07 06:03:01,736 - INFO - Success 75CE68ADA9244799B393E817E1211FE6
出土信息提取进度:  54%|█████▍    | 56/103 [00:08<00:03, 12.11it/s]2026-04-07 06:03:01,954 - INFO - Success 684c6decb03142fdb4352a61caa7b90f
2026-04-07 06:03:02,058 - INFO - Success e879f9d2d39b4c4bba485951d140cb44
出土信息提取进度:  56%|█████▋    | 58/103 [00:08<00:04, 10.12it/s]2026-04-07 06:03:02,222 - INFO - Success 3063e6ad9a1547eca51482572e153955
2026-04-07 06:03:02,533 - INFO - Success ea99e925505e490bb1467c305e936c02
出土信息提取进度:  58%|█████▊    | 60/103 [00:08<00:05,  7.67it/s]2026-04-07 06:03:03,236 - INFO - Success f266ee4b7deb4acc8dba0cc731426fff
2026-04-07 06:03:03,265 - INFO - Success 32636BAC0D2846A38F0F234CFCB2B370
出土信息提取进度:  60%|██████    | 62/103 [00:09<00:07,  5.31it/s]2026-04-07 06:03:03,403 - INFO - Success fb33423d06fc419895a0d94874699e45
出土信息提取进度:  61%|██████    | 63/103 [00:09<00:07,  5.53it/s]2026-04-07 06:03:03,409 - INFO - Success 78463EFA3274413DAFA2E8EDD2BF3B40
2026-04-07 06:03:03,582 - INFO - Success fbf2dfc78ee94fc88cd02e717fbbbbbc
出土信息提取进度:  63%|██████▎   | 65/103 [00:09<00:05,  6.52it/s]2026-04-07 06:03:03,592 - INFO - Success 31771fe34dc8454788f892ed431e0772
2026-04-07 06:03:03,624 - INFO - Success 32E8374BDF354B4799333FA3F5B2515B
2026-04-07 06:03:03,767 - INFO - Success 7DE761E18BDB436DA9EF1488BE67BA78
出土信息提取进度:  66%|██████▌   | 68/103 [00:10<00:04,  8.50it/s]2026-04-07 06:03:03,891 - INFO - Success 7db8cb2d4594444d8ef36f8bc18436d6
2026-04-07 06:03:03,946 - INFO - Success 7dd9fda13a674bcdbfe13a3bd50569fd
出土信息提取进度:  68%|██████▊   | 70/103 [00:10<00:03,  9.08it/s]2026-04-07 06:03:03,976 - INFO - Success ffc96d5649c149ccb391212191c620f1
2026-04-07 06:03:04,028 - INFO - Success 3700000201862104A090408131348015
2026-04-07 06:03:04,068 - INFO - Success 3700000201862104A090408152441015
出土信息提取进度:  71%|███████   | 73/103 [00:10<00:02, 11.83it/s]2026-04-07 06:03:04,100 - INFO - Success 7e53f11efc8d4982a90d76273e889d7c
2026-04-07 06:03:04,284 - INFO - Success 3700000201862104A090423144432247
出土信息提取进度:  73%|███████▎  | 75/103 [00:10<00:02, 11.04it/s]2026-04-07 06:03:04,380 - INFO - Success 84D6541D56734C1DA5BF5F83A9F72061
2026-04-07 06:03:04,476 - INFO - Success 3700000201862104A090423153605434
出土信息提取进度:  75%|███████▍  | 77/103 [00:10<00:02, 10.86it/s]2026-04-07 06:03:04,494 - INFO - Success 75b16c6c35eb4c08ac2f19e2939ce38c
2026-04-07 06:03:04,860 - INFO - Success 87b189b7df94410b8116edd02d941a61
出土信息提取进度:  77%|███████▋  | 79/103 [00:11<00:02,  8.35it/s]2026-04-07 06:03:05,142 - INFO - Success 3700000201862104A090423155039965
2026-04-07 06:03:05,860 - INFO - Success 97cd990698544433ac7676cb2b523d48
出土信息提取进度:  79%|███████▊  | 81/103 [00:12<00:05,  4.38it/s]2026-04-07 06:03:05,889 - INFO - Success 8813991421974fc6ae985b8e56f98e7b
2026-04-07 06:03:05,891 - INFO - Success 98e3f6acbf3c4d399ccd4fd3bd3be9be
2026-04-07 06:03:05,991 - INFO - Success 3700000201862104A090424151743359
出土信息提取进度:  82%|████████▏ | 84/103 [00:12<00:03,  6.33it/s]2026-04-07 06:03:06,005 - INFO - Success 3700000201862104A090423160817512
2026-04-07 06:03:06,039 - INFO - Success 3700000201862104B100420135017250
2026-04-07 06:03:06,137 - INFO - Success 3700000201862104B100420125357046
出土信息提取进度:  84%|████████▍ | 87/103 [00:12<00:01,  8.36it/s]2026-04-07 06:03:06,139 - INFO - Success 9CDD93EDA34D433481B553E903A60213
2026-04-07 06:03:06,177 - INFO - Success 3700000201862104B100420135604875
2026-04-07 06:03:06,308 - INFO - Success 3700000201862104B100420153205453
出土信息提取进度:  87%|████████▋ | 90/103 [00:12<00:01, 10.12it/s]2026-04-07 06:03:06,363 - INFO - Success 9aa49e35723d4d21ad10428348eeb45c
2026-04-07 06:03:06,367 - INFO - Success 9EEC82C715A44FF09E025496524BDC51
2026-04-07 06:03:06,652 - INFO - Success 9dbffd2582464ae79b34b9a40549dcb2
出土信息提取进度:  90%|█████████ | 93/103 [00:13<00:01,  9.63it/s]2026-04-07 06:03:06,655 - INFO - Success A35948EDC4444AB8ABD4B13FF392D439
2026-04-07 06:03:06,712 - INFO - Success 3700000201862104B100420163857687
2026-04-07 06:03:06,744 - INFO - Success 3700000201862104B100420193644406
2026-04-07 06:03:06,751 - INFO - Success 3700000201862104B100420155310218
2026-04-07 06:03:06,927 - INFO - Success ABAD9B57EF0942C9BE29692DF70DABA1
出土信息提取进度:  95%|█████████▌| 98/103 [00:13<00:00, 12.10it/s]2026-04-07 06:03:07,285 - INFO - Success C04719446A1A4F4D9379E6B8AFE2E7E0
2026-04-07 06:03:07,897 - INFO - Success 3700000201862104B100424093722877
出土信息提取进度:  97%|█████████▋| 100/103 [00:14<00:00,  6.15it/s]2026-04-07 06:03:08,090 - INFO - Success 3700000201862104B100424102035706
2026-04-07 06:03:08,098 - INFO - Success 3700000201862104B100424103745799
出土信息提取进度:  99%|█████████▉| 102/103 [00:14<00:00,  6.71it/s]2026-04-07 06:03:08,239 - INFO - Success CB5FD05583A04BD3934C07F01F89F572
出土信息提取进度: 100%|██████████| 103/103 [00:14<00:00,  7.04it/s]

✅ 所有出土信息提取完成！原始结果已存入: d:\LocalWorkSpace\20260202_museum_data_crawling\wwsdw.net\data\extracted\excavation_20260407_060253.jsonl

In [ ]:
import os

if os.path.exists(OUTPUT_EXC_FILE):
    # 读取提取的结果
    extracted_exc = []
    with open(OUTPUT_EXC_FILE, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                extracted_exc.append(json.loads(line))
    
    if extracted_exc:
        df_exc = pd.DataFrame(extracted_exc)
        
        # 通过 id 设置索引，保证严格对齐
        df_merged.set_index("id", inplace=True)
        df_exc.set_index("id", inplace=True)
        
        # 只更新有实际提取结果的行，其余保持我们第一步设置的 null 字典
        df_merged["excavationLocation"].update(df_exc["excavationLocation"])
        df_merged["excavationDate"].update(df_exc["excavationDate"])
        
        # 恢复 id 为普通列
        df_merged.reset_index(inplace=True)
        
        print("✅ 出土信息已成功合并回 df_merged！")
else:
    print("没有生成提取文件，说明全是空值，已全部打底为 null，无需合并。")

In [64]:
default_location = {"country": None, "province": None, "city": None, "district": None, "specificAddress": None, "coordinate": None}
df_merged[df_merged["excavationLocation"]!=default_location].head(5)

,id,name,era,culture,time,dimensionsDesc,structuredDimensions,fullDesc,features,excavationLocation,...,yearName,material,pattern,shape,state,color,craft,raw_excavation_info,raw_size_in_desc,other_info
16,01210ea5cbb14a6ea6de870299758873,新石器时代龙山文化黑陶觯,新石器时代,龙山文化,"{'year': None, 'month': None, 'day': None}",高*口径*底径：14*6.6*4.1,"[{'unit': 'cm', 'value': 14.0, 'deviation': No...",新石器时代龙山文化，饮酒器。泥质黑陶，侈口圆唇，高颈，鼓腹下收，小平底。口径6.6cm、底径...,"[{'label': 'material', 'value': '泥质黑陶'}, {'lab...","{'country': '中国', 'province': '山东省', 'city': '...",...,新石器时代,泥质黑陶,None,侈口圆唇，高颈，鼓腹下收，小平底,None,黑陶,None,1979年于日照尧王城遗址发掘,口径6.6cm、底径4.1cm、高14cm，重190g,新石器时代龙山文化，饮酒器。日照市博物馆收藏。国家二级文物。
88,063f04237365413588b166fadfa28e1c,新石器时代大汶口文化刻陶文“钺”“拍”灰陶尊,新石器时代,大汶口文化,"{'year': None, 'month': None, 'day': None}",高67、口径32、壁厚2.4,"[{'unit': 'cm', 'value': 67.0, 'deviation': No...",为新石器时代大汶口文化陶尊。1960年莒县陵阳河遗址出土。通高63厘米、口径39厘米、壁厚2...,"[{'label': 'material', 'value': '夹砂黄褐陶'}, {'la...","{'country': '中国', 'province': '山东省', 'city': '...",...,新石器时代,夹砂黄褐陶,口沿下和腹下各饰两道凹弦纹，弦纹间饰有两周圆圈纹。通体饰篮纹。腹部刻有符号“钺”形，另一面刻...,折沿，深直腹，尖底,保存较好,涂有朱红,刻,1960年莒县陵阳河遗址出土,通高63厘米、口径39厘米、壁厚2.4厘米,墓主人以此来陪葬，生前可能是一位军事首领。从发掘墓葬出土的人体多为不全者来看，这意味着在50...
101,06b6eb96528a4fe68887b0658eeaaf78,新石器时代龙山文化陶鬶,新石器时代,龙山文化,"{'year': None, 'month': None, 'day': None}",通高36.8厘米，口径11.6厘米,"[{'unit': 'cm', 'value': 36.8, 'deviation': No...",侈口，口沿下饰两周不透镂孔，一道凸玄纹至流两侧并饰有乳钉纹，鸟啄形流上仰，颈呈筒形，颈腹分界...,"[{'label': 'pattern', 'value': '口沿下饰两周不透镂孔，一道凸...","{'country': None, 'province': None, 'city': '沂...",...,新石器时代,None,口沿下饰两周不透镂孔，一道凸玄纹至流两侧并饰有乳钉纹，腹上两侧饰盲鼻，并饰一周凸玄纹,侈口，鸟啄形流上仰，颈呈筒形，颈腹分界明显，乳状袋足，绳索状鋬,None,None,镂空,沂水县杨庄镇杨庄村出土,通高36.8厘米，口径11.6厘米，重1.09千克,None
102,0706381701a34e0ca5ff8bc75a9428a9,新石器时代大汶口文化彩陶漩涡纹单耳杯,新石器时代,大汶口文化,"{'year': None, 'month': None, 'day': None}",口径*底径：8.9*8,"[{'unit': 'cm', 'value': 8.9, 'deviation': Non...",该器物为泥质红陶，侈口，圆唇，高领，鋬状桥式耳，缓折腹下垂，小平底。唇内外及下腹饰黑彩一周，...,"[{'label': 'material', 'value': '泥质红陶'}, {'lab...","{'country': '中国', 'province': '山东省', 'city': '...",...,新石器时代,泥质红陶,腹部用黑彩绘成旋涡纹,侈口，圆唇，高领，鋬状桥式耳，缓折腹下垂，小平底,口沿两处略残,唇内外及下腹饰黑彩一周，腹折线以上饰红陶衣,None,广饶县傅家遗址出土，属新石器时代大汶口文化时期遗物，距今已有5000多年的历史,None,对研究鲁北地区大汶口文化提供了重要的实物资料
128,07b866fcbb5547bd80a464f74fa0fbc0,新石器时代龙山文化黑陶壶,新石器时代,龙山文化,"{'year': None, 'month': None, 'day': None}",高*口径*底径*腹径：16.6*8.4*5.5*11.9,"[{'unit': 'cm', 'value': 16.6, 'deviation': No...",新石器时代龙山文化，酒器或水器。泥质黑陶，侈口，圆唇，高领，鼓腹，腹上部饰二道凹弦纹及二个对...,"[{'label': 'material', 'value': '泥质黑陶'}, {'lab...","{'country': '中国', 'province': '山东省', 'city': '...",...,新石器时代,泥质黑陶,None,侈口，圆唇，高领，鼓腹，腹上部饰二道凹弦纹及二个对称的横耳，鼓腹下收，小平底,None,黑陶,None,采集于日照两城镇遗址,口径8.4cm、底径5.5cm、腹径11.9cm、高16.6cm，重366g,新石器时代龙山文化，酒器或水器。日照市博物馆收藏。国家二级文物。

In [65]:
default_date = {"year": None, "month": None, "day": None}
df_merged[df_merged["excavationDate"]!=default_date].head(5)

,id,name,era,culture,time,dimensionsDesc,structuredDimensions,fullDesc,features,excavationLocation,...,yearName,material,pattern,shape,state,color,craft,raw_excavation_info,raw_size_in_desc,other_info
16,01210ea5cbb14a6ea6de870299758873,新石器时代龙山文化黑陶觯,新石器时代,龙山文化,"{'year': None, 'month': None, 'day': None}",高*口径*底径：14*6.6*4.1,"[{'unit': 'cm', 'value': 14.0, 'deviation': No...",新石器时代龙山文化，饮酒器。泥质黑陶，侈口圆唇，高颈，鼓腹下收，小平底。口径6.6cm、底径...,"[{'label': 'material', 'value': '泥质黑陶'}, {'lab...","{'country': '中国', 'province': '山东省', 'city': '...",...,新石器时代,泥质黑陶,None,侈口圆唇，高颈，鼓腹下收，小平底,None,黑陶,None,1979年于日照尧王城遗址发掘,口径6.6cm、底径4.1cm、高14cm，重190g,新石器时代龙山文化，饮酒器。日照市博物馆收藏。国家二级文物。
88,063f04237365413588b166fadfa28e1c,新石器时代大汶口文化刻陶文“钺”“拍”灰陶尊,新石器时代,大汶口文化,"{'year': None, 'month': None, 'day': None}",高67、口径32、壁厚2.4,"[{'unit': 'cm', 'value': 67.0, 'deviation': No...",为新石器时代大汶口文化陶尊。1960年莒县陵阳河遗址出土。通高63厘米、口径39厘米、壁厚2...,"[{'label': 'material', 'value': '夹砂黄褐陶'}, {'la...","{'country': '中国', 'province': '山东省', 'city': '...",...,新石器时代,夹砂黄褐陶,口沿下和腹下各饰两道凹弦纹，弦纹间饰有两周圆圈纹。通体饰篮纹。腹部刻有符号“钺”形，另一面刻...,折沿，深直腹，尖底,保存较好,涂有朱红,刻,1960年莒县陵阳河遗址出土,通高63厘米、口径39厘米、壁厚2.4厘米,墓主人以此来陪葬，生前可能是一位军事首领。从发掘墓葬出土的人体多为不全者来看，这意味着在50...
150,09053083EC594D80BF074EBF18C9994B,新石器时代大汶口文化附加堆纹夹砂红陶三足鼎,None,None,"{'year': None, 'month': None, 'day': None}",None,NaN,新石器时代大汶口文化时期\r\n未定级\r\n2012年出土于界石旸里店遗址，现藏威海市文登...,"[{'label': 'material', 'value': '夹砂红褐陶'}, {'la...","{'country': None, 'province': None, 'city': '威...",...,新石器时代,夹砂红褐陶,下腹部饰1圈弦纹,尖唇，折沿，略鼓腹，裆略平，柱状足,两足略残,None,None,2012年出土于界石旸里店遗址，现藏威海市文登区博物馆。,口径10.4厘米，腹径11.6厘米，柱足长4.4厘米，通高12.2厘米。,新石器时代大汶口文化时期，未定级，明器，陶质。
203,0C1D1E0DA1424A318CA9DC8A4139FBBD,新石器时代龙山文化单耳陶杯,新石器时代,龙山文化,"{'year': None, 'month': None, 'day': None}",口径*底径*最大宽：6*4.8*13.8,"[{'unit': 'cm', 'value': 6.0, 'deviation': Non...",1989年山东邹平丁公遗址出土\r\n水器。泥质黑陶，器表经磨光，直筒形，口微侈，中部略内收...,"[{'label': 'material', 'value': '泥质黑陶'}, {'lab...","{'country': '中国', 'province': '山东', 'city': No...",...,新石器时代,泥质黑陶,None,直筒形，口微侈，中部略内收，细高体，底内凹，把手宽扁长，位于器身的底部。整体造型独特。,None,黑陶,器表经磨光,1989年山东邹平丁公遗址出土,None,水器。
266,0e17c26e26d4481c80697ebb7fff3a28,大汶口文化褐陶鬶,None,None,"{'year': None, 'month': None, 'day': None}",None,NaN,1976年9月出土于火山埠遗址\r\n 高21.6厘米,"[{'label': 'material', 'value': '褐陶'}]","{'country': None, 'province': None, 'city': No...",...,新石器时代,褐陶,None,None,None,None,None,1976年9月出土于火山埠遗址,高21.6厘米,None

In [66]:
# 为统一起见，将excavationDate为默认值的行的excavationDate字段全部置为 null
df_merged.loc[df_merged["excavationDate"] == default_date, "excavationDate"] = None

In [68]:
# 去掉以下的列："image_count" "local_image_paths" "pictureIds" "yearName" "material" "pattern" "shape" "state" "color" "craft"
df_merged.drop(columns=["image_count", "local_image_paths", "pictureIds", "yearName", "material", "pattern", "shape", "state", "color", "craft"], inplace=True)

In [69]:
final_output_path = BASE_DIR / "data" / "final_delivery.jsonl"
df_merged.to_json(final_output_path, orient="records", lines=True, force_ascii=False)